# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 10:23
from __future__ import unicode_literals

import blogApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(default=1, on_delete=models.SET(blogApp.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
