# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20160408_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(blank=True, default='images_folder/none/no-img.jpg', upload_to='os.path.join(BASE_DIR, "images_folder", "articles")'),
        ),
    ]
