# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_auto_20160408_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
