# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogApp', '0008_auto_20160409_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='banned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-user']},
        ),
        migrations.AddField(
            model_name='article',
            name='read_later',
            field=models.ManyToManyField(related_name='_article_read_later_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.CharField(choices=[('R', 'DRAFT'), ('P', 'PUBLISHED'), ('A', 'APPROVED'), ('D', 'DELETED')], default='R', max_length=30),
        ),
    ]
