# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_auto_20160410_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_add_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_update_date',
            new_name='update_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_status',
        ),
        migrations.AddField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
