# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_auto_20160411_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='draft',
            new_name='publish',
        ),
    ]
